//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryRecipes
    {
        public CategoryRecipes()
        {
            this.Recipes = new HashSet<Recipes>();
        }
    
        public int F_CATEGORY_ID { get; set; }
        public string F_CAT_NAME { get; set; }
        public string F_CAT_URL { get; set; }
    
        public virtual ICollection<Recipes> Recipes { get; set; }
    }
}
