//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostProduct
    {
        public long F_COST_ID { get; set; }
        public decimal F_COST { get; set; }
        public System.DateTime F_DATEFROM { get; set; }
        public System.DateTime F_DATETO { get; set; }
        public int F_PRODUCT_ID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
