//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public Recipes()
        {
            this.Structure = new HashSet<Structure>();
            this.BlackListRecipes = new HashSet<BlackListRecipes>();
        }
    
        public int F_RECIPE_ID { get; set; }
        public Nullable<int> F_CAT_ID { get; set; }
        public string F_NAME { get; set; }
        public string F_URL { get; set; }
        public decimal F_CALORIES { get; set; }
        public decimal F_PROTEINS { get; set; }
        public decimal F_CARBONYDRATES { get; set; }
        public decimal F_FATS { get; set; }
    
        public virtual CategoryRecipes CategoryRecipes { get; set; }
        public virtual ICollection<Structure> Structure { get; set; }
        public virtual ICollection<BlackListRecipes> BlackListRecipes { get; set; }
    }
}
