//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.BlackListIngredient = new HashSet<BlackListIngredient>();
            this.BlackListProduct = new HashSet<BlackListProduct>();
            this.BlackListRecipes = new HashSet<BlackListRecipes>();
            this.WhiteListProduct = new HashSet<WhiteListProduct>();
        }
    
        public int F_USER_ID { get; set; }
        public string F_LOGIN { get; set; }
        public string F_PASSWORD { get; set; }
    
        public virtual ICollection<BlackListIngredient> BlackListIngredient { get; set; }
        public virtual ICollection<BlackListProduct> BlackListProduct { get; set; }
        public virtual ICollection<BlackListRecipes> BlackListRecipes { get; set; }
        public virtual ICollection<WhiteListProduct> WhiteListProduct { get; set; }
    }
}
