//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CATEGORY
    {
        public int F_CAT_ID { get; set; }
        public string F_CAT_NAME { get; set; }
        public string F_CAT_URL { get; set; }
        public string F_CAT_PARENT_NAME { get; set; }
    }
}
