//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_INGREDIENTPRODUCT
    {
        public string F_NAME { get; set; }
        public string f_nameproduct { get; set; }
        public int F_INGREDIENT_ID { get; set; }
        public int F_PRODUCT_ID { get; set; }
    }
}
